spring:
  profiles:
    active: local

---

spring:
  profiles:
    group:
      "local":
        - test-db
      "prod1":
        - mysql-db
        - port1
      "prod2":
        - mysql-db
        - port2

---

spring:
  config:
    activate:
      on-profile: test-db

  datasource:
    url: jdbc:h2:tcp://localhost/~/study/codesquad/team_project/airbnb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: debug    # sout이 아닌 logger를 이용해 SQL 출력
        type: trace   # 쿼리 값 확인

---

spring:
  config:
    activate:
      on-profile: port1

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: port2

server:
  port: 8082
